CREATE DATABASE BBDCONFIG
GO

CREATE TABLE TBD(
	NOM NVARCHAR(50) PRIMARY KEY, --PK
)
SELECT *  FROM TBD
DELETE FROM TBD WHERE NOM = 'CLIENTES2'

CREATE TABLE TBDATRIBUTOS(
	NOMTD NVARCHAR(50),-- FK DE TBD
	NOMATRIBUTO NVARCHAR(50), --PK
	TIPODATO NVARCHAR(50),
	PRIMARY KEY ( NOMATRIBUTO),
    FOREIGN KEY (NOMTD) REFERENCES TBD(NOM)
)

SELECT * FROM TBDATRIBUTOS
DELETE FROM TBDATRIBUTOS WHERE NOMTD = 'CLIENTES2'

CREATE TABLE FRAGMENTO(
	NOMTD NVARCHAR(50), --PK, FK DE TBD
	NOMFRAGMENTO NVARCHAR(50), --PK
	NOMBDD NVARCHAR (50),
	TIPOBDD NVARCHAR (50),
	DIRECCIONIP NVARCHAR(50),
	USUARIO NVARCHAR(50),
	CONTRASEÑA NVARCHAR(50),
	ESTADO CHAR(1),
	ZONADISTRIBUCION NVARCHAR(50), --FK DE CRITERIODISTRIBUCION
	PRIMARY KEY (NOMTD, NOMFRAGMENTO),
    FOREIGN KEY (NOMTD) REFERENCES TBD(NOM),
)
select * from FRAGMENTO

SELECT * FROM FRAGMENTO WHERE ZONADISTRIBUCION = 'NORTE'
delete from FRAGMENTO WHERE NOMBDD = 'POSTGRESQL'
CREATE TABLE CRITERIODISTRIBUCION(
	ZONAGEOGRAFICA NVARCHAR(50), --PK
	ESTADO NVARCHAR (30), --PK
	PRIMARY KEY (ZONAGEOGRAFICA, ESTADO)
)
--inserts Criterio distribucion
-- Insertar estados de la región Norte
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Norte', 'Baja California');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Norte', 'Baja California Sur');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Norte', 'Chihuahua');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Norte', 'Coahuila');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Norte', 'Durango');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Norte', 'Nuevo León');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Norte', 'Sinaloa');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Norte', 'Sonora');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Norte', 'Tamaulipas');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Norte', 'Zacatecas');

-- Insertar estados de la región Centro
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Aguascalientes');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Colima');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Ciudad de México');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Guanajuato');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Hidalgo');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Jalisco');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Estado de México');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Michoacán');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Morelos');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Nayarit');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Puebla');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Querétaro');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'San Luis Potosí');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Centro', 'Tlaxcala');

-- Insertar estados de la región Sur
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Sur', 'Campeche');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Sur', 'Chiapas');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Sur', 'Guerrero');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Sur', 'Oaxaca');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Sur', 'Quintana Roo');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Sur', 'Tabasco');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Sur', 'Veracruz');
INSERT INTO CRITERIODISTRIBUCION (ZONAGEOGRAFICA, ESTADO) VALUES ('Sur', 'Yucatán');

select * from CRITERIODISTRIBUCION WHERE ESTADO = 'SINALOA'