/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package bdd.front;

import bddback.ConfigBDD;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author soule
 */
public class CrearTabla extends javax.swing.JDialog {

    /**
     * Creates new form CrearTabla
     */
    public CrearTabla(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBox(tblAtributos, tblAtributos.getColumnModel().getColumn(1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCLOSE = new javax.swing.JButton();
        lblNomTabla = new javax.swing.JLabel();
        btnSAVE = new javax.swing.JButton();
        txtNomTablaDistribuida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtributos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCLOSE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCLOSE.setText("CERRAR");
        btnCLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLOSEActionPerformed(evt);
            }
        });

        lblNomTabla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomTabla.setText("Nom.Tabla distribuida");

        btnSAVE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSAVE.setText("GUARDAR");
        btnSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAVEActionPerformed(evt);
            }
        });

        tblAtributos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblAtributos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Atributos", "Tipo Dato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAtributos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomTabla)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomTablaDistribuida))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCLOSE, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomTabla)
                    .addComponent(txtNomTablaDistribuida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCLOSE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLOSEActionPerformed
        // TODO add your handling code here:
        if (ConfigBDD.connectBDD()) {
            System.out.println("bdd.front.frmConfiguracion.btnSAVEActionPerformed()");
        }
    }//GEN-LAST:event_btnCLOSEActionPerformed

        public void setBox(JTable tblAtributos, TableColumn columna){
        JComboBox c = new JComboBox();
        c.addItem("INT");
        c.addItem("MONEY");
        c.addItem("VARCHAR");
        
        columna.setCellEditor(new DefaultCellEditor(c));
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setToolTipText("Seleccionar Dato");
        columna.setCellRenderer(renderer);
    }

    private void btnSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAVEActionPerformed
        // TODO add your handling code here:
        // Obtener el nombre de la tabla
        String NomTabla = txtNomTablaDistribuida.getText();

        // Obtener nombres de los atributos
        int totalFilas = tblAtributos.getRowCount();
        String[] nomCampos = new String[totalFilas];
        String[] tipoDato = new String[totalFilas];

        for (int i = 0; i < totalFilas; i++) {
            // Obtener el nombre del campo desde la columna 0
            nomCampos[i] = tblAtributos.getValueAt(i, 0).toString();

            // Obtener el tipo de dato desde la columna 1
            Object valorCelda = tblAtributos.getValueAt(i, 1);

            if (valorCelda instanceof JComboBox) {
                // Si la celda contiene un JComboBox, obtener el valor seleccionado
                JComboBox comboBox = (JComboBox) valorCelda;
                tipoDato[i] = comboBox.getSelectedItem().toString();
            } else {
                // Si la celda ya tiene un valor definido, simplemente obtener el valor como String
                tipoDato[i] = valorCelda.toString();
            }

            System.out.println(nomCampos[i] + " - Tipo de dato: " + tipoDato[i]);
        }
        if(ConfigBDD.createTable(NomTabla, nomCampos, tipoDato)){
            Rutinas.MensajesPantalla.TareaconExito("Tabla Creada Con Exito");
            System.out.println("insertados correctamente (cazmbiar a  showdialog)");
        }else{
            Rutinas.MensajesPantalla.TareaconFallo("Error al crear La Tabla Verifique los datos");
            System.out.println("error al insertar los datos");
        }

    }//GEN-LAST:event_btnSAVEActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCLOSE;
    private javax.swing.JButton btnSAVE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomTabla;
    private javax.swing.JTable tblAtributos;
    private javax.swing.JTextField txtNomTablaDistribuida;
    // End of variables declaration//GEN-END:variables
}
