/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package bdd.front;
import bddback.ConfigBDD;
import javax.swing.JOptionPane;

/**
 *
 * @author soule
 */
public class CrearFragmento extends javax.swing.JDialog {

    /**
     * Creates new form CrearFragmento
     */
    public CrearFragmento(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ConfigBDD.llenarComboTabla(CbxTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgrpEstado = new javax.swing.ButtonGroup();
        lblNomTabla = new javax.swing.JLabel();
        CbxZona = new javax.swing.JComboBox<>();
        lblnomFragmento = new javax.swing.JLabel();
        txtNomFragmento = new javax.swing.JTextField();
        lblTipoBBD = new javax.swing.JLabel();
        cbxGestores = new javax.swing.JComboBox<>();
        lblIP = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        lblZonaDistribucion = new javax.swing.JLabel();
        CbxTabla = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        rbActivo = new javax.swing.JRadioButton();
        RbInactivo = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        lblnombdd = new javax.swing.JLabel();
        txtNomBDD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNomTabla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomTabla.setText("Nombre Tabla Distribuida");

        CbxZona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CbxZona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NORTE", "CENTRO", "SUR" }));

        lblnomFragmento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblnomFragmento.setText("Nom Fragmento");

        txtNomFragmento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblTipoBBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipoBBD.setText("Gestor BDD");

        cbxGestores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxGestores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MYSQL", "SQL SERVER", "POSTGRESQL" }));

        lblIP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIP.setText("Direccion IP");

        txtIP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContraseña.setText("Contraseña");

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblZonaDistribucion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblZonaDistribucion.setText("ZonaDistribucion");

        CbxTabla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setText("Estado");

        bgrpEstado.add(rbActivo);
        rbActivo.setText("Activo");

        bgrpEstado.add(RbInactivo);
        RbInactivo.setText("Inactivo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblnombdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblnombdd.setText("NOM BDD");

        txtNomBDD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomTabla)
                                .addGap(18, 18, 18)
                                .addComponent(CbxTabla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblnomFragmento, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomFragmento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblnombdd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbxGestores, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtNomBDD))))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoBBD)
                                    .addComponent(lblIP))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblZonaDistribucion)
                            .addComponent(lblEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbActivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RbInactivo)
                                .addContainerGap())
                            .addComponent(CbxZona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblContraseña)
                            .addComponent(lblUsuario))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomTabla)
                    .addComponent(CbxTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnomFragmento)
                    .addComponent(txtNomFragmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombdd)
                    .addComponent(txtNomBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoBBD)
                    .addComponent(cbxGestores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIP)
                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContraseña)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblZonaDistribucion)
                    .addComponent(CbxZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(rbActivo)
                    .addComponent(RbInactivo))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String Estado;
        if (rbActivo.isSelected()) {
            Estado = "A";
        } else if(RbInactivo.isSelected()){
            Estado = "B";
        } else{
            JOptionPane.showMessageDialog(null, "Seleccione un Estado del Fragmento", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        ConfigBDD.InsertarFragmento(CbxTabla.getSelectedItem().toString(), txtNomFragmento.getText(), cbxGestores.getSelectedItem().toString(),txtNomBDD.getText(), txtIP.getText(), txtUsuario.getText(), txtContraseña.getText(), Estado, CbxZona.getSelectedItem().toString());
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxTabla;
    private javax.swing.JComboBox<String> CbxZona;
    private javax.swing.JRadioButton RbInactivo;
    private javax.swing.ButtonGroup bgrpEstado;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxGestores;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblNomTabla;
    private javax.swing.JLabel lblTipoBBD;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblZonaDistribucion;
    private javax.swing.JLabel lblnomFragmento;
    private javax.swing.JLabel lblnombdd;
    private javax.swing.JRadioButton rbActivo;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtNomBDD;
    private javax.swing.JTextField txtNomFragmento;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
