/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_ago_dic.frmView;

import BDMG.ConexionBD;
import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author soule
 */
public class frInserts extends javax.swing.JDialog {

    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos csv", "csv");
    private DefaultTableModel tableModel;
    private ConexionBD conexion;
    
    public frInserts(javax.swing.JFrame Padre, ConexionBD conexion) {
        super(Padre, "frInserts", true);
        this.tableModel = new DefaultTableModel();
        this.conexion = conexion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grp1 = new javax.swing.ButtonGroup();
        btnInsertar = new javax.swing.JButton();
        lblRutaArchivo = new javax.swing.JLabel();
        txtRutaArchivo = new javax.swing.JTextField();
        btnFileChooser = new javax.swing.JButton();
        txtNomArchivo = new javax.swing.JTextField();
        lblNomArchivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCSV = new javax.swing.JTable();
        RbtTicketD = new javax.swing.JRadioButton();
        rbTicketH = new javax.swing.JRadioButton();

        btnInsertar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        lblRutaArchivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRutaArchivo.setText("Ruta del archivo");

        txtRutaArchivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnFileChooser.setText("....");
        btnFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileChooserActionPerformed(evt);
            }
        });

        txtNomArchivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblNomArchivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomArchivo.setText("Nombre del archivo");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos a insertar"));

        tblCSV.setModel(tableModel);
        jScrollPane1.setViewportView(tblCSV);

        grp1.add(RbtTicketD);
        RbtTicketD.setText("on TicketD");

        grp1.add(rbTicketH);
        rbTicketH.setText("on TicketH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRutaArchivo)
                            .addComponent(txtNomArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomArchivo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RbtTicketD)
                                    .addComponent(rbTicketH))))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblRutaArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RbtTicketD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbTicketH)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFileChooser, txtRutaArchivo});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        if (rbTicketH.isSelected()) {
             conexion.Insert(txtRutaArchivo.getText(), true);
        } else{
            conexion.Insert(txtRutaArchivo.getText(), false);
        }
       
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileChooserActionPerformed
        JFileChooser filechoose = new JFileChooser();
        filechoose.setFileFilter(filter);
        int opcion = filechoose.showOpenDialog(this);
        
        if (opcion == JFileChooser.APPROVE_OPTION) {
            
            //se obtiene el nombre del archivo seleccionado
            String rutaArchivo = filechoose.getSelectedFile().getPath();
            
            //obtener la ruta del archivo seleccionado
            String nombreArchivo = filechoose.getSelectedFile().getName();
            
            txtNomArchivo.setText(nombreArchivo);
            txtRutaArchivo.setText(rutaArchivo);
            
            LoadDataCSV(rutaArchivo);
        }
    }//GEN-LAST:event_btnFileChooserActionPerformed

    public void LoadDataCSV(String rutaArchivo){
        String linea;
        String separador = ",";

        try (BufferedReader br = new BufferedReader(new FileReader(rutaArchivo))) {
            // Leer la primera línea (encabezados)
            if ((linea = br.readLine()) != null) {
                String[] encabezados = linea.split(separador);
                for (String encabezado : encabezados) {
                    tableModel.addColumn(encabezado);
                    System.out.println(encabezado);
                }
            }
            // Leer las líneas restantes (datos)
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(separador);
                tableModel.addRow(datos);
            }
            System.out.println("Número de filas agregadas: " + tableModel.getRowCount());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbtTicketD;
    private javax.swing.JButton btnFileChooser;
    private javax.swing.JButton btnInsertar;
    private javax.swing.ButtonGroup grp1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomArchivo;
    private javax.swing.JLabel lblRutaArchivo;
    private javax.swing.JRadioButton rbTicketH;
    private javax.swing.JTable tblCSV;
    private javax.swing.JTextField txtNomArchivo;
    private javax.swing.JTextField txtRutaArchivo;
    // End of variables declaration//GEN-END:variables
}
